server.port=8086
spring.application.name=ms-calificaciones

spring.datasource.url=jdbc:mysql://localhost:3306/db_calificaciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

ms.estudiantes.url=http://localhost:8081
ms.asignaturas.url=http://localhost:8085